#pragma once

#undef DEBOUNCE
#undef IGNORE_MOD_TAP_INTERRUPT
#undef ONESHOT_TIMEOUT
#undef QMK_KEYS_PER_SCAN
#undef TAPPING_TERM

#define RETRO_TAPPING

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 3000
#define QMK_KEYS_PER_SCAN 4
#define TAPPING_TERM 200

#define RGBLIGHT_SPLIT
#define RGBLIGHT_DEFAULT_VAL RGBLIGHT_LIMIT_VAL / 2

#define COMBO_TERM 50
#define COMBO_COUNT 1

#define EE_HANDS
