#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_VARIABLE_LEN

#undef QMK_KEYS_PER_SCAN
#define QMK_KEYS_PER_SCAN 4

#undef TAPPING_TERM
#define TAPPING_TERM 20

#undef RETRO_TAPPING
#define RETRO_TAPPING

#undef IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT

#undef USB_POLLING_INTERVAL_MS
#define USB_POLLING_INTERVAL_MS 10
