#undef DEBOUNCE
#undef IGNORE_MOD_TAP_INTERRUPT
#undef ONESHOT_TIMEOUT
#undef QMK_KEYS_PER_SCAN
#undef TAPPING_TERM
#undef USB_POLLING_INTERVAL_MS

#define IGNORE_MOD_TAP_INTERRUPT
#define RETRO_TAPPING

#define DEBOUNCE 10
#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 3000
#define QMK_KEYS_PER_SCAN 4
#define TAPPING_TERM 200
#define USB_POLLING_INTERVAL_MS 2
