#pragma once

#undef PLOOPY_DPI_OPTIONS
#undef PLOOPY_DPI_DEFAULT

#define PLOOPY_DPI_NORMAL_VALUE 1200
#define PLOOPY_DPI_SNIPER_VALUE 600
#define PLOOPY_DPI_OPTIONS { PLOOPY_DPI_NORMAL_VALUE }
#define PLOOPY_DPI_DEFAULT 0
